- izlistati sve foldere sa filmovima unutar cineme URADJENO
- izlistati sve foldere unutar filmova URADJENO
- razlikovati srt od mkv i avi i mp4 formata URADJENO
-ako ima 2 srt.srt, ukloniti jedan srt URADJENO
- kopirati isti naziv i dodati odgovarajuce nastavke URADJENO
- Aako je subs prije filma, dobija naziv onog filma prije njega - POPRAVITI
- ako ima folder subs sa vise titloova, sve ih nazvati po filmu - POPRAVITI
- rijesiti se tackica - POPRAVITI
